# Configs to train model
# features
categorical_features:
  - "player_id"
  - "player_team_id"
  - "home_team_id"
  - "ground_id"
  - "international_class_id"
  - "floodlit"
  - "neutral_match"
  - "international_valid"
  - "followon"
  - "rain_rule"
  - "target_id"

numerical_features:
  - "days_extended"
  - "actual_days"

# response
response: "target_value"

input_fp: "/Users/juichanglu/work/startup/mamba_model/data/cricket_traning_data.csv"
model_fp: "chkpt"
best_model_name: 'factorization_machine_model.pth'

epoch: 100
learning_rate: 1e-3
batch_size: 32
weight_decay: 1e-6
save_dir: "chkpt"
loss_plot_fp: "loss_plot.png"
