# Configs to train model
# features
categorical_features:
  - "player_id"
  - "player_team_id"
  - "home_team_id"
  - "opponent_team_id"
  - "ground_id"
  - "international_class_id"
  - "floodlit"
  - "neutral_match"
  - "international_valid"
  - "followon"
  - "rain_rule"
  - "target_id"
  - "is_home"

numerical_features:
  - "days_extended"
  - "actual_days"
  - "current_age"
  - "batting_order"

# response
response: "target_value"
response_binary: "target_value_binary"

training_input_fp: "data/ODI_cricket_training_data.csv"
model_fp: "chkpt"
best_model_name: 'factorization_machine_model'
loss_plot_fp: "loss_curves"
confusion_matrix_fp: "confusion_matrix"
eval_metrics_fp: "eval_metrics"

inference_input_fp: "data/match_to_predict.csv"

training_sample_size: null
# the following two params are fixed to 0 and 70 respectively when model_stage is classification
target_lower_limit: 0
target_upper_limit: 70

model_stage: "classification" #"classification" or "regression"
classification_target_threshold: 20
minority_sample_limit: 10
minority_sampling_categories: ["player_id", "target_id", "target_value"]
stratefied_sampling_categories: ["player_id", "target_id"]

allowed_initial_loss_diff: 0.5

epoch: 40
learning_rate: 1e-5
batch_size: 16
weight_decay: 1e-8
embedding_dim: 20
attention_dim: 20
hidden_layers: [32]
