# Configs to train model
# features
categorical_features:
  - "player_id"
  - "player_team_id"
  - "home_team_id"
  - "ground_id"
  - "international_class_id"
  - "floodlit"
  - "neutral_match"
  - "international_valid"
  - "followon"
  - "rain_rule"
  - "target_id"

numerical_features:
  - "days_extended"
  - "actual_days"

# response
response: "target_value"

training_input_fp: "data/cricket_traning_data.csv"
inference_input_fp: "data/cricket_traning_data.csv"
model_fp: "chkpt"
best_model_name: 'factorization_machine_model.pth'


training_sample_size: 10000
target_lower_limit: 10
target_upper_limit: 200
minority_sample_limit: 10
minority_sampling_categories: ["player_id", "target_id", "target_value"]
stratefied_sampling_categories: ["target_id"]
allowed_initial_loss_diff: 0.5
epoch: 100
learning_rate: 5e-4
batch_size: 16
weight_decay: 1e-8
embedding_dim: 20
attention_dim: 20

save_dir: "chkpt"
loss_plot_fp: "loss_plot.png"
