# Configs to train model
# features
categorical_features:
  - "player_id"
  - "player_team_id"
  - "home_team_id"
  - "opponent_team_id"
  - "ground_id"
  - "position_id"
  - "style_id"
  - "floodlit"
  - "neutral_match"
  - "international_valid"
  - "rain_rule"
  - "target_id"
  - "is_home"
  - "actual_days"

numerical_features:
  - "current_age"
  - "batting_order"
  - 'mt'
  - 'inns'
  - 'rn'
  - 'fo'
  - 'si'
  - 'ft'
  - 'hn'
  - 'bf'
  - 'dk'
  - 'times_not_out'
  - 'hs'
  - 'bta'
  - 'btsr'
#  - 'host_mt'
#  - 'host_inns'
#  - 'host_rn'
#  - 'host_fo'
#  - 'host_si'
#  - 'host_ft'
#  - 'host_hn'
#  - 'host_bf'
#  - 'host_dk'
#  - 'host_times_not_out'
#  - 'host_hs'
#  - 'host_bta'
#  - 'host_btsr'
#  - 'opposition_mt'
#  - 'opposition_inns'
#  - 'opposition_rn'
#  - 'opposition_fo'
#  - 'opposition_si'
#  - 'opposition_ft'
#  - 'opposition_hn'
#  - 'opposition_bf'
#  - 'opposition_dk'
#  - 'opposition_times_not_out'
#  - 'opposition_hs'
#  - 'opposition_bta'
#  - 'opposition_btsr'
#  - 'batting_positionval1_mt'
#  - 'batting_positionval1_inns'
#  - 'batting_positionval1_rn'
#  - 'batting_positionval1_fo'
#  - 'batting_positionval1_si'
#  - 'batting_positionval1_ft'
#  - 'batting_positionval1_hn'
#  - 'batting_positionval1_bf'
#  - 'batting_positionval1_dk'
#  - 'batting_positionval1_times_not_out'
#  - 'batting_positionval1_hs'
#  - 'batting_positionval1_bta'
#  - 'batting_positionval1_btsr'

skewed_features:
  - 'mt'
  - 'inns'
  - 'rn'
  - 'fo'
  - 'si'
  - 'ft'
  - 'hn'
  - 'bf'
  - 'dk'
  - 'times_not_out'
  - 'host_mt'
  - 'host_inns'
  - 'host_rn'
  - 'host_fo'
  - 'host_si'
  - 'host_ft'
  - 'host_hn'
  - 'host_bf'
  - 'host_dk'
  - 'host_times_not_out'
  - 'host_hs'
  - 'opposition_mt'
  - 'opposition_inns'
  - 'opposition_rn'
  - 'opposition_fo'
  - 'opposition_si'
  - 'opposition_ft'
  - 'opposition_hn'
  - 'opposition_bf'
  - 'opposition_dk'
  - 'opposition_times_not_out'
  - 'opposition_hs'
  - 'opposition_bta'
  - 'batting_positionval1_mt'
  - 'batting_positionval1_inns'
  - 'batting_positionval1_rn'
  - 'batting_positionval1_fo'
  - 'batting_positionval1_si'
  - 'batting_positionval1_ft'
  - 'batting_positionval1_hn'
  - 'batting_positionval1_bf'
  - 'batting_positionval1_dk'
  - 'batting_positionval1_times_not_out'
  - 'batting_positionval1_hs'
  - 'batting_positionval1_bta'

# response
response: "target_value"
response_binary: "target_value_binary"

training_input_fp: "data/ODI_cricket_training_data.csv"
model_fp: "chkpt"
best_model_name: 'factorization_machine'
loss_plot_fp: "loss_curves"
confusion_matrix_fp: "confusion_matrix"
eval_metrics_fp: "eval_metrics"

inference_input_fp: "data/match_to_predict.csv"

training_sample_size: null
# the following two params are fixed to 0 and 70 respectively when model_stage is classification
target_lower_limit: 0
target_upper_limit: 70

model_stage: "classification" #"classification" or "regression"
classification_target_threshold: [0, 20, 70]
minority_sample_limit: 10
minority_sampling_categories: ["player_id", "target_id", "target_value"]
stratefied_sampling_categories: ["player_id", "target_id"]

allowed_initial_loss_diff: 0.5

epoch: 60
learning_rate: 1e-5
batch_size: 16
weight_decay: 1e-8
embedding_dim: 20
attention_dim: 20
hidden_layers: [32]
